### ISSUE TITLE
Closing one session kills other sessions

### ISSUE THREAD

**Issue by moethu** [moethu/webg3n#9]
On closing a single session, other running sessions get closed because the g3n app is crashing.

**Comment by moethu** [comment]
```
panic: NotInitialized: The GLFW library is not initialized

goroutine 311 [running, locked to thread]:
github.com/go-gl/glfw/v3.2/glfw.acceptError(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/max.thumfart/go/src/github.com/go-gl/glfw/v3.2/glfw/error.go:173 +0x1d1
github.com/go-gl/glfw/v3.2/glfw.panicError()
        /home/max.thumfart/go/src/github.com/go-gl/glfw/v3.2/glfw/error.go:184 +0x32
github.com/go-gl/glfw/v3.2/glfw.(*Window).ShouldClose(0xc000120300, 0x4a464f9)
        /home/max.thumfart/go/src/github.com/go-gl/glfw/v3.2/glfw/window.go:309 +0x3e
engine/window.(*glfwWindow).ShouldClose(0xc000220160, 0x943ece)
        /home/max.thumfart/go/src/engine/window/glfw.go:412 +0x2f
engine/util/application.(*Application).Run(0xc0000a49c0, 0x0, 0x0)
        /home/max.thumfart/go/src/engine/util/application/application.go:420 +0x177
main.load3DApplication(0xc0000a49c0, 0xc0009d8000, 0x24, 0x320, 0x320, 0xc0009d0060, 0xc0009d00c0, 0xc0009cc090, 0xe)
        /home/max.thumfart/go/src/g3nserverside/main.go:58 +0x1d2
created by main.serveWebsocket
        /home/max.thumfart/go/src/g3nserverside/server.go:132 +0x4c4
```

**Comment by moethu** [comment]
The glfwManager contains data shared by all windows, probably it gets closed when closing one session.
